# Generated by Django 4.2.11 on 2025-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
