# Generated by Django 4.2.11 on 2025-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
