# Generated by Django 4.2.11 on 2025-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_enrollment_age_remove_enrollment_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('username_org', models.CharField(blank=True, max_length=255, null=True)),
                ('reconciled_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('reconciled_territory', models.CharField(blank=True, max_length=255, null=True)),
                ('reconciled_languages', models.JSONField(blank=True, null=True)),
                ('reconciled_projects', models.JSONField(blank=True, null=True)),
                ('reconciled_want_to_learn', models.JSONField(blank=True, null=True)),
                ('reconciled_want_to_share', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
