# Generated by Django 4.2.11 on 2025-08-01 14:42

from django.db import migrations, models

def populate_user_field(apps, schema_editor):
    Enrollment = apps.get_model('enrollments', 'Enrollment')
    for enrollment in Enrollment.objects.all():
        enrollment.user = enrollment.data.get("user", "")
        enrollment.save()

    # Remove duplicate enrollments based on the user field
    unique_enrollments = {}
    for enrollment in Enrollment.objects.all():
        user = enrollment.user
        if user not in unique_enrollments:
            unique_enrollments[user] = enrollment
        else:
            existing_enrollment = unique_enrollments[user]
            for key in set(enrollment.data.keys()):
                if enrollment.data[key]:
                    existing_enrollment.data[key] = enrollment.data[key]
                    existing_enrollment.save()
            enrollment.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_profile'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(populate_user_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.CharField(max_length=255, unique=True, null=False, blank=False),
        ),
    ]
