# Generated by Django 5.1.9 on 2025-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_badge_userbadge'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('enrollments', 'UserBadge').objects.all().update(
                verification_code=models.F('verification_code')[54:]
            ),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='verification_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
