# Generated by Django 5.1.9 on 2025-09-10 14:58

from django.db import migrations, models


def slice_verification_code(apps, schema_editor):
    userbadge = apps.get_model('enrollments', 'UserBadge')
    for badge in userbadge.objects.all():
        badge.verification_code = badge.verification_code[-10:]
        badge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_badge_userbadge'),
    ]

    operations = [
        migrations.RunPython(
            slice_verification_code,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='verification_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
